name: Setup Bun
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  setup-bun:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        bun-version:
          - latest
          - canary
          - "0.5.6"
          - "0.6.11"
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v3
      - id: setup-bun
        name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: ${{ matrix.bun-version }}
      - id: verify-bun
        name: Verify Bun
        run: |
          bun --version
